version: '3'

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "82:80"
    links:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    restart: always
    container_name: php-fpm
    volumes:
      - ./:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./composer.phar:/app/composer.phar
    links:
      - mysql

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
